### ISSUE TITLE
errors with conditionalValidation 

### ISSUE THREAD

**Issue by DVSneuro** [bids-standard/bids2nda#24]
Hi -- I used bids2nda successfully back in February, but now it doesn't seem to work because I think the NDA validator has added some new conditional validation steps (see below). For example, image_file_format was set to NIFTI last time and it remains set that way this time. But, now it needs scanner_software_versions_pd to have a value, and it doesn't seem like bids2nda populates that field (or maybe it's missing from my data)?

Thanks!
David

```
84c8344f-9ad6-4f49-b063-f4b6a414805c	image03	error	conditionalValidation	1	scanner_software_versions_pd	Field scanner_software_versions_pd is conditionally required when image_file_format != 'DICOM'
84c8344f-9ad6-4f49-b063-f4b6a414805c	image03	error	conditionalValidation	2	scanner_software_versions_pd	Field scanner_software_versions_pd is conditionally required when image_file_format != 'DICOM'
84c8344f-9ad6-4f49-b063-f4b6a414805c	image03	error	conditionalValidation	3	scanner_software_versions_pd	Field scanner_software_versions_pd is conditionally required when image_file_format != 'DICOM'
84c8344f-9ad6-4f49-b063-f4b6a414805c	image03	error	conditionalValidation	4	experiment_id	Field experiment_id is conditionally required when scan_type == 'fMRI'
84c8344f-9ad6-4f49-b063-f4b6a414805c	image03	error	conditionalValidation	4	scanner_software_versions_pd	Field scanner_software_versions_pd is conditionally required when image_file_format != 'DICOM'
84c8344f-9ad6-4f49-b063-f4b6a414805c	image03	error	conditionalValidation	5	experiment_id	Field experiment_id is conditionally required when scan_type == 'fMRI'
```

**Comment by obenshaindw** [comment]
It looks like the bids2nda is looking for it. https://github.com/bids-standard/bids2nda/blob/master/bids2nda/main.py#L218 and yes it does look like this became a conditionally required field instead of a recommended field on 26 Feb 2019.

**Comment by DVSneuro** [comment]
Thanks, David! Looks like part of the issue was tied to me using an older version of bids2nda, but the latest version still isn't populating some conditionally required fields correctly according to the validator (photomet_interpret, image_slice_thickness, image_orientation). But, I don't really understand what's going on there because only one of those fields (photomet_interpret) appears to be empty (and I'm honestly not sure what would even go in that field). 

And thanks for getting back to me on the NDA helpdesk! I'm trying to implement Yarik's fix for the image03.txt generated by bids2nda, but I think I'm confused about what the middle chunk of code with the sed statement is replacing. 
```
tr '\t' ',' < /data/NDA/output_v2/image03.tsv | sed -e 's,/data/R01/bids/Brain/wpc-7642/,,g' -e 's,/data/NDA/output_v2/,,g' >| /data/NDA/output_v2/image03.csv
```
Is `/data/R01/bids/Brain/wpc-7642/` supposed to be the path to my BIDS directory (image_file) or the meta data in data_file2?

**Comment by obenshaindw** [comment]
@DVSneuro the sed statement is using -e flag, which allows you to chain together multiple sed statements on the same input line. It looks like this might be converting absolute path on BOTH image_file and data_file2 columns to relative path by stripping /data/R01/bids/Brain/wpc-7642/ and /data/NDA/output_v2/ from image03.csv.

**Comment by DVSneuro** [comment]
Thanks, David! I think you're right, and I got everything to upload after this fix and manually populating the experiment_id and photomet_interpret fields.
