### ISSUE TITLE
image03.txt empty

### ISSUE THREAD

**Issue by vnckppl** [bids-standard/bids2nda#28]
I have a bids dataset that I validated using the online validator. The validator recognizes all subjects/sessions/files/etc. and returns no errors.

I created a subject to GUID table in plain text format that looks like:
```
sub-1 - NDAR<randomID>
sub-2 - NDAR<randomID>
sub-3 - NDAR<randomID>
```

When I run 
`bids2nda /path/to/bids/root /path/to/GUIDtable.txt /path/to/output/folder
`
the file 'image03.txt' is being created in the output folder.
This content of this file is:

> "image" "3"

bids2nda returns:

> Metadata extraction complete

No errors.

Does anyone have an idea why no metadata is written to the image03.txt file?

**Comment by dowdlelt** [comment]
For my GUID key I do not have the `sub` component, I simply have
`01 - NDAR<randomid>`

as my folders are named sub-01, sub-02, etc

Perhaps try `1 - NDARetc`

**Comment by vnckppl** [comment]
Thanks for the suggestion! I tried this, but it is creating the same empty image03.txt file and it returns the same message to the terminal ('Metadata extraction complete.).

**Comment by vnckppl** [comment]
It turned out that bids2nda does not work with nii files, only with gzipped nii files.
