### ISSUE TITLE
FLAIR file naming: key error

### ISSUE THREAD

**Issue by vnckppl** [bids-standard/bids2nda#29]
When I run bids2nda I get the following error for a FLAIR image:

> Traceback (most recent call last):
>   File "/usr/local/bin/bids2nda", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/bids2nda/main.py", line 380, in main
>     run(args)
>   File "/usr/local/lib/python2.7/dist-packages/bids2nda/main.py", line 212, in run
>     dict_append(image03_dict, 'scan_type', suffix_to_scan_type[suffix])
> KeyError: 'FLAIR'

My FLAIR files are named:

```
anat/sub-01_ses-01_acq-Ax_FLAIR.nii.gz
anat/sub-01_ses-01_acq-ISO_FLAIR.nii.gz
```

What would be the correct way of naming these FLAIR images that does not interfere with bids2nda?

**Comment by RobertJirsaraie** [comment]
I think the following formatting would work! Fingers crossed! 

anat/sub-01_ses-01_acq-FLAIRax_T2w.nii.gz
anat/sub-01_ses-01_acq-FLAIRiso_T2w.nii.gz

**Comment by vnckppl** [comment]
Thank you RobertJirsaraie for your reply. Your suggestion works, but it is more of a workaround rather than a solution since it brakes the BIDS convention.

**Comment by obenshaindw** [comment]
@vnckppl I added mapping in suffix_to_scan_type dictionary for FLAIR suffix to NDA image03 SCAN_TYPE of FLAIR. I believe this should resolve the issue.
